{
  "CMN_E00001": "The fatal error was occurred.",
  "CMN_E00002": "The specified data could not be handled, because it has been updated by the other terminal.",
  "CMN_E00003": "Invalid operation, unable to handle it.",
  "CMN_E00004": "The specified data is already registered.",
  "CMN_E00005": "SQL statement acquisition failed with the given data select name \"{0}\".",
  "CMN_E00006": "You have no permission to register.",
  "CMN_E00007": "You have no permission to update.",
  "CMN_E00008": "You have no permission to delete.",
  "CMN_E00009": "You have no permission to search.",
  "CMN_E00010": "I input user ID, a password, and, please log in.",
  "CMN_N00011": "The processing was finished correctly.",
  "CMN_E00012": "The specified data can not be updated, because it has been updated by other users.",
  "CMN_E00013": "The details for the registration do not exist.",
  "CMN_E00014": "The details for the update do not exist.",
  "CMN_E00015": "The details for the delete do not exist.",
  "CMN_E00016": "The specified data does not exist.",
  "CMN_E00017": "The specified data is already registered.",
  "CMN_E00018": "Please enter required item {0}.",
  "CMN_E00019": "Please enter half-width alphanumeric characters in {0}.",
  "CMN_E00020": "{0} is too short. Please enter in the {1} or more characters.",
  "CMN_E00021": "{0} is too long. Please enter at {1} characters or less.",
  "CMN_E00022": "Please enter the half-width numbers in the {0}.",
  "CMN_E00023": "Please enter a value greater than or equal to {1} in {0}.",
  "CMN_E00024": "Please enter a value less than or equal to {1} in {0}.",
  "CMN_E00025": "Please enter full-width characters in {0}.",
  "CMN_E00026": "Please enter half-width characters in {0}.",
  "CMN_E00027": "Please enter {1} digits in {0}.",
  "CMN_E00028": "{0} is duplicated.",
  "CMN_E00029": "Please enter at {0} characters.",
  "CMN_E00030": "Data form is invalid. Please choose the file of the designated form.",
  "CMN_E00031": "There are invalid data in the upload file. Please confirm it.",
  "CMN_E00032": "An error occurred during file creating.",
  "CMN_N00033": "Upload processing...Please wait...",
  "CMN_N00034": "Download processing...Please wait...",
  "CMN_E00035": "Error occurred.<br \/>(Batch registration is canceled.)<br \/><br \/>Please check the error list, fix erros, and retry upload.",
  "CMN_N00036": "Processing...Please wait...",
  "CMN_E00037": "Invalid process ID.",
  "CMN_E00038": "The value of {0} is not exists.",
  "CMN_N00039": "Cancel the processing. Is it OK?",
  "CMN_N00040": "Now start processing. Is it OK?",
  "CMN_N00041": "Register it. Is it OK?",
  "CMN_N00042": "Update it. Is it OK?",
  "CMN_N00043": "Delete it. Is it OK?",
  "CMN_E00044": "Please select target data.",
  "CMN_N00045": "Start download the error list. Is it OK?",
  "CMN_E00046": "The wait window closed under processing. Process completion has not been comfirmed.",
  "CMN_N00047": "Output it. Is it OK?",
  "lbl_CMN_ADDITION": "Add",
  "lbl_CMN_CANCEL": "Cancel",
  "lbl_CMN_CLEARALL": "Clear all",
  "lbl_CMN_CLOSE": "Close",
  "lbl_CMN_CMBSELECT": "-Select-",
  "lbl_CMN_CONFIRMATION": "Check",
  "lbl_CMN_DECISION": "Select",
  "lbl_CMN_DETAILED": "Detail",
  "lbl_CMN_DOWNLOAD": "Download",
  "lbl_CMN_ELIMINATION": "Delete",
  "lbl_CMN_ERRORLIST": "Error list",
  "lbl_CMN_INFORMATION": "Information",
  "lbl_CMN_LOGIN": "Login",
  "lbl_CMN_LOGINID": "Login ID",
  "lbl_CMN_MENU": "Menu",
  "lbl_CMN_NEXT": "Next page",
  "lbl_CMN_PASSWORD": "Password",
  "lbl_CMN_PREVIOUS": "Previous page",
  "lbl_CMN_REFERRING": "Refer",
  "lbl_CMN_REGISTRATION": "Insert",
  "lbl_CMN_RENEWAL": "Update",
  "lbl_CMN_RESULT": "Result",
  "lbl_CMN_SEARCH": "Search",
  "lbl_CMN_SELECTALL": "Select all",
  "lbl_CMN_UPLOAD": "Upload",
  "lbl_ZZ_COMMENT": "Comment",
  "lbl_ZZ_CSVMODELWRITER": "CsvWriter(Model)",
  "lbl_ZZ_CSVWRITER": "CsvWriter",
  "lbl_ZZ_CSVWRITESAMPLE": "CsvWriter Sample",
  "lbl_ZZ_DETAIL": "Detail",
  "lbl_ZZ_DETAILLIST": "DetailList",
  "lbl_ZZ_DETAILNO": "DetailNo",
  "lbl_ZZ_DOWNLOADPATTERN": "Download pattern",
  "lbl_ZZ_ERRORDESC": "Error Description",
  "lbl_ZZ_FIXEDMODELWRITER": "TxtWriter(Model)",
  "lbl_ZZ_INSDATE": "InsDate",
  "lbl_ZZ_ITEMCD": "ItemCd",
  "lbl_ZZ_ITEMNM": "ItemNm",
  "lbl_ZZ_ITEMQUANTITY": "ItemQuantity",
  "lbl_ZZ_KEYCD": "Key Code",
  "lbl_ZZ_LIST": "List",
  "lbl_ZZ_LISTCD": "ListCode",
  "lbl_ZZ_LISTDETAILMUPATTERN": "List => Detail => Update format pattern",
  "lbl_ZZ_LISTDETAILPATRERN": "List → detail format (updated) pattern",
  "lbl_ZZ_LISTDETAILSEARCHPATTERN": "List → detail format (search) pattern",
  "lbl_ZZ_LISTDOWNLOADPATTERN": "List => Download format pattern",
  "lbl_ZZ_LISTLISTDETAILPATTERN": "List => List => detail format pattern",
  "lbl_ZZ_LISTMUMIPATTERN": "List form (plural update and registration) pattern",
  "lbl_ZZ_LISTMUSIPATTERN": "List form (plural update and single registration) pattern",
  "lbl_ZZ_LISTSEARCHPATTERN": "List (search) pattern",
  "lbl_ZZ_MULTIUPDATE": "MultiUpdate",
  "lbl_ZZ_REGISTRATIONDATA": "Registration data",
  "lbl_ZZ_ROWNO": "Row No",
  "lbl_ZZ_RYAKUSYOHANKAKU": "Abbreviation(half)",
  "lbl_ZZ_RYAKUSYOZENKAKU": "Abbreviation(full)",
  "lbl_ZZ_SALESID": "SalesId",
  "lbl_ZZ_SEARCHDIALOGPATTERN": "Search dialog pattern",
  "lbl_ZZ_SINGLESEARCHPATTERN": "Single sheet (search) pattern",
  "lbl_ZZ_SINGLEUPDATEPATTERN": "Single sheet (update) pattern",
  "lbl_ZZ_SUJICD": "NumberCode",
  "lbl_ZZ_SUMMONEY": "SumMoney",
  "lbl_ZZ_UNITPRICE": "UnitPrice",
  "lbl_ZZ_UPDATELISTPATTERN": "Upload => List format pattern",
  "lbl_ZZ_UPLOADPATTERN": "Upload pattern",
  "lbl_ZZ_SAMPLEMENU": "Sample Menu",
  "lbl_ZZ_EXCELTEMPLATE": "Excel Template",
  "lbl_ZZ_MERGEPRINT": "Merge Print",
  "lbl_ZZ_ERRORITEM": "Error Item",
  "CMN_E00048": "Please enter the half-width decimal-number in the {0}.",
  "CMN_E00049": "Please enter {1} characters for decimal part of {0}.",
  "CMN_E00050": "Please enter half-width alphabet characters in {0}.",
  "CMN_E00051": "Please enter half-width katakana characters in {0}.",
  "CMN_E00052": "Please enter valid date with yyyyMMdd format in {0}.",
  "CMN_E00053": "Please enter valid year-month with yyyyMM format in {0}.",
  "CMN_E00054": "Since login failed 3 times, the form has been locked.",
  "CMN_E00058": "{0} mismatch.",
  "CMN_E00059": "Please include both alphbet and number in {0}.",
  "lbl_CMN_LOGOUT": "Logout",
  "lbl_CMN_LANGUAGE": "Language",
  "CMN_E00060": "The search results has exceeded the system upper limit, so processing was interrupted."
}
